[workspace]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
platforms = ["linux-64"]
preview = ["pixi-build"]

[package]
name = "mujoco_simulate"
version = "3.7.0"

[build-system]
build-backend = { name = "pixi-build-cmake", version = "*" }

channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[tasks]

[dependencies]
mujoco_simulate = { path = "." }
mujoco = { path = "../" }

[host-dependencies]
glfw = ">=3.4,<4"
libgl-devel = "*"
